import React, { useState, useEffect, useRef } from 'react';
import { coachService } from '../core/coachService';
import { X, Send, Sword, Trash2, Settings, Loader, Key } from 'lucide-react';

const CoachChat = ({ currentDate, onClose }) => {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [apiKey, setApiKey] = useState(coachService.getApiKey());
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    const history = coachService.getChatHistory();
    if (history.length === 0) {
      setMessages([{
        role: 'coach',
        content: "I'm The Spartan. I don't do pleasantries. Show me your schedule, tell me your excuses, or ask me what to do. But don't waste my time.",
        timestamp: new Date().toISOString(),
        source: 'local'
      }]);
    } else {
      setMessages(history);
    }
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    const text = input.trim();
    if (!text || sending) return;

    setInput('');
    setSending(true);

    const userMsg = {
      role: 'user',
      content: text,
      timestamp: new Date().toISOString()
    };
    setMessages(prev => [...prev, userMsg]);

    try {
      const response = await coachService.chat(text, currentDate);
      setMessages(prev => [...prev, response]);
    } catch (e) {
      setMessages(prev => [...prev, {
        role: 'coach',
        content: "Connection failed. But you don't need me to tell you what to do. You already know. Go do it.",
        timestamp: new Date().toISOString(),
        source: 'local'
      }]);
    }

    setSending(false);
    inputRef.current?.focus();
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleClearChat = () => {
    coachService.clearChatHistory();
    setMessages([{
      role: 'coach',
      content: "Clean slate. But remember — erasing the conversation doesn't erase what you did or didn't do. Now talk.",
      timestamp: new Date().toISOString(),
      source: 'local'
    }]);
  };

  const handleSaveApiKey = () => {
    coachService.setApiKey(apiKey);
    setShowSettings(false);
  };

  const formatTime = (timestamp) => {
    if (!timestamp) return '';
    const d = new Date(timestamp);
    const h = d.getHours() % 12 || 12;
    const m = d.getMinutes().toString().padStart(2, '0');
    const ampm = d.getHours() >= 12 ? 'PM' : 'AM';
    return `${h}:${m} ${ampm}`;
  };

  return (
    <div className="fixed inset-0 bg-black/60 flex items-end sm:items-center justify-center z-50">
      <div className="bg-charcoal border-t sm:border border-purple-light w-full max-w-md sm:rounded-xl rounded-t-xl h-[90vh] sm:h-[80vh] flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-purple-light/30 flex items-center justify-between shrink-0">
          <div className="flex items-center space-x-2">
            <Sword size={20} className="text-purple-400" />
            <div>
              <h2 className="text-base font-semibold text-white">The Spartan</h2>
              <span className="text-xs text-gray-500">
                {coachService.hasApiKey() ? 'LLM Connected' : 'Local Mode'}
              </span>
            </div>
          </div>
          <div className="flex items-center space-x-1">
            <button
              onClick={() => setShowSettings(!showSettings)}
              className="touch-target text-gray-400 hover:text-purple-400 transition-colors"
              title="Settings"
            >
              <Settings size={18} />
            </button>
            <button
              onClick={handleClearChat}
              className="touch-target text-gray-400 hover:text-red-400 transition-colors"
              title="Clear chat"
            >
              <Trash2 size={18} />
            </button>
            <button
              onClick={onClose}
              className="touch-target text-gray-400 hover:text-white transition-colors"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* API Key Settings Panel */}
        {showSettings && (
          <div className="p-4 border-b border-purple-light/30 bg-deep-black shrink-0">
            <div className="flex items-center space-x-2 mb-2">
              <Key size={14} className="text-purple-400" />
              <span className="text-sm font-medium text-gray-300">OpenAI API Key</span>
            </div>
            <p className="text-xs text-gray-500 mb-2">
              Optional. Without it, The Spartan runs in local mode with pre-built responses.
              With it, responses are generated by a high-reasoning LLM.
            </p>
            <div className="flex space-x-2">
              <input
                type="password"
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                placeholder="sk-..."
                className="flex-1 px-3 py-2 bg-charcoal border border-purple-light rounded-lg text-white text-sm placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
              />
              <button
                onClick={handleSaveApiKey}
                className="touch-target px-3 py-2 bg-purple-600 text-white text-sm rounded-lg hover:bg-purple-700 transition-colors"
              >
                Save
              </button>
            </div>
          </div>
        )}

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {messages.map((msg, i) => (
            <div
              key={i}
              className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div
                className={`max-w-[85%] rounded-lg px-3 py-2 ${
                  msg.role === 'user'
                    ? 'bg-purple-900/40 border border-purple-700/50'
                    : 'bg-deep-black border-l-2 border-purple-500'
                }`}
              >
                {msg.role === 'coach' && (
                  <div className="flex items-center space-x-1 mb-1">
                    <Sword size={10} className="text-purple-400" />
                    <span className="text-[10px] font-medium text-purple-400 uppercase tracking-wider">
                      Spartan
                    </span>
                  </div>
                )}
                <p className="text-sm text-gray-200 leading-relaxed">{msg.content}</p>
                <span className="text-[10px] text-gray-600 mt-1 block text-right">
                  {formatTime(msg.timestamp)}
                </span>
              </div>
            </div>
          ))}
          {sending && (
            <div className="flex justify-start">
              <div className="bg-deep-black border-l-2 border-purple-500 rounded-lg px-3 py-2">
                <Loader size={16} className="text-purple-400 animate-spin" />
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="p-4 border-t border-purple-light/30 shrink-0">
          <div className="flex space-x-2">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Speak. No excuses."
              rows={1}
              className="flex-1 px-3 py-2 bg-deep-black border border-purple-light rounded-lg text-white text-sm placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none"
            />
            <button
              onClick={handleSend}
              disabled={!input.trim() || sending}
              className="touch-target px-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <Send size={18} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CoachChat;
